language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Travis doesn't support pypy5.6
#  - "pypy-5.6.0"
cache: pip
# command to install dependencies
install: pip install -U setuptools tox-travis -r requirements.txt -r requirements-test.txt
# command to run tests
script: py.test --cov